parent_env = Environment()

params = Variables(['custom.py'])
params.Add(('releaseVersion', 'Release version (string)', '1.0'))
params.Update(parent_env)

SConscript(dirs='.', variant_dir='build', duplicate=0, exports='parent_env')
