schema_version = "1.0.0"
id = "democap_tools"
version = "{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}"
name = "DEMoCap Tools"
tagline = "Tools for importing DEMoCap motion captures into Blender"
maintainer = "DragonDreams GmbH <info@dragondreams.ch>"
type = "add-on"
website = "https://dragondreams.ch/index.php/democap-dragengine-motion-capture/"
tags = [
  "Import-Export",
  "Animation"
]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later"
]
copyright = [
  "2024 DragonDreams GmbH",
]
[permissions]
"files" = "Loading motion capture files"
"network" = "Connect to DEMoCap (Live Connection)"
