name: BuildMsix

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      versionDelga:
        required: true
        type: string
      artifactDistribute:
        required: true
        type: string
      artifactMsix:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Install required packages
        run: sudo apt -y install scons
      
      - name: Get Distribution
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactDistribute }}
      
      - name: Copy DELGA
        run: |
          cp -a DEMoCap-${{ inputs.version }}.msix distribute/DEMoCap-${{ inputs.versionDelga }}.msix
        
      - name: Build MSIX
        working-directory: installer/msappstore
        run: |
          scons releaseVersion=${{ inputs.version }} delgaVersion=${{ inputs.versionDelga }}
        
      - name: Copy MSXI
        run: |
          cp -a installer/msappstore/build/DEMoCap-${{ inputs.version }}.msix DEMoCap-${{ inputs.version }}.msix
        
      - name: Store MSIX
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: DEMoCap-${{ inputs.version }}.msix
          if-no-files-found: error
