name: Distribute

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: 'recursive'
      
      - name: Distribute
        id: distribute
        uses: LordOfDragons/build-delga@v1
        with:
          projectFile: 'DEMoCap.degp'
          profile: 'Release'
        
      - name: Store DELGA
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: distribute/DEMoCap-${{ inputs.version }}.delga
          if-no-files-found: error
