name: Distribute

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Create LFS file hash list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-objects-id

      - name: Restore LFS Cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: lfs-cache-${{ hashFiles('.lfs-objects-id') }}
          restore-keys: lfs-cache-

      - name: Git LFS Pull
        run: |
          git lfs pull 2>&1 | tee lfs.log
          if grep -q "error:" "lfs.log" ; then
            exit 1
          fi
      
      - name: Install required packages
        run: sudo apt -y install scons
      
      - name: Distribute
        id: distribute
        uses: LordOfDragons/build-delga@v1
        with:
          projectFile: 'DEMoCap.degp'
          profile: 'Release'
        
      - name: Rename distribution file
        run: |
          cp -a distribute/DEMoCap.delga DEMoCap-${{ inputs.version }}.delga
        
      - name: Build Blender scripts
        working-directory: tools/blender
        run: |
          scons releaseVersion=${{ inputs.version }}
        
      - name: Copy Blender scripts
        run: |
          cp -a tools/blender/build/blender-democap-tools-${{ inputs.version }}.zip blender-democap-tools-${{ inputs.version }}.zip
        
      - name: Store DELGA
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: |
            DEMoCap-${{ inputs.version }}.delga
            blender-democap-tools-${{ inputs.version }}.zip
          if-no-files-found: error
