name: Distribute

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Find LFS Cache Files
      - run: |
          git lfs ls-files -l | cut -d' ' -f1 | sort > .assets-id

      - name: Restore LFS Cache
      - restore_cache:
          key: lfs-cache-{{ checksum ".assets-id" }}

      - name: Pull LFS Objects
      - run: |
          git lfs pull

      - name: Save LFS Cache
      - save_cache:
          key: lfs-cache-{{ checksum ".assets-id" }}
          paths:
            - .git/lfs
        
      - name: Update project file
        run: |
          sed -i -e 's/DEMoCap-[0-9.]\+.delga/DEMoCap-${{ inputs.version }}.delga/g' project.xml
      
      - name: Distribute
        id: distribute
        uses: LordOfDragons/build-delga@v1
        with:
          projectFile: 'DEMoCap.degp'
          profile: 'Release'
        
      - name: Store DELGA
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: distribute/DEMoCap-${{ inputs.version }}.delga
          if-no-files-found: error
