name: Nightly

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  distribute:
    uses: ./.github/workflows/distribute.yml
    with:
      version: nightly
      artifact: distribution
      lfscache: true

  blender:
    uses: ./.github/workflows/blender.yml
    with:
      version: nightly
      artifact: blender

  buildmsix:
    needs: [distribute]
    uses: ./.github/workflows/buildmsix.yml
    with:
      version: nightly
      versionDelga: 9999
      artifactDistribute: distribution
      artifactMsix: msix

  upload:
    needs: [distribute, blender]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Distribution
        uses: actions/download-artifact@v4
        with:
          name: distribution
      
      - name: Get Blender Scripts
        uses: actions/download-artifact@v4
        with:
          name: blender
      
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      
      - name: Sign Artifacts
        run: |
          files=(
            DEMoCap-nightly.delga
            blender-democap-tools-nightly.zip
            )
          for file in "${files[@]}"; do
            gpg2 --personal-digest-preferences SHA512 --armor --yes --detach-sign \
              --local-user A58A91BCA5C3B2C34CD57ACB8040F88D27F1D0AA \
              --output "${file}.asc" $file
          done
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Update git tag
        run: |
          git tag -f nightly
          git push -f origin nightly
      
      - name: Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          draft: false
          prerelease: true
          commit: 'main'
          tag: 'nightly'
          name: 'DEMoCap Pre-Release Nightly Build'
          body: |
            Continuous Nightly Build of DEMoCap.
            Created: ${{ steps.date.outputs.date }}
            
            Builds are potentially unstable. Use at own risk.
            
            GPG signatures for all files are included as .asc files.
          artifacts: >
            DEMoCap-nightly.delga,
            blender-democap-tools-nightly.zip,
            *.asc
