name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: 'X.Y{.Z}'
      dragengineVersion:
        description: 'Drag[en]gine Version'
        required: true
        type: string
        default: 'X.Y{.Z}'

jobs:
  distribute:
    uses: ./.github/workflows/distribute.yml
    with:
      version: ${{ github.event.inputs.version }}
      artifact: distribution
      lfscache: false

  blender:
    uses: ./.github/workflows/blender.yml
    with:
      version: ${{ github.event.inputs.version }}
      artifact: blender

  buildmsix:
    needs: [distribute]
    uses: ./.github/workflows/buildmsix.yml
    with:
      version: ${{ github.event.inputs.version }}
      artifactDistribute: distribution
      artifactMsix: msix

  upload:
    needs: [distribute, blender]
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Distribution
        uses: actions/download-artifact@v4
        with:
          name: distribution
      
      - name: Get Blender Scripts
        uses: actions/download-artifact@v4
        with:
          name: blender
      
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      
      - name: Sign Artifacts
        run: |
          files=(
            DEMoCap-${{ github.event.inputs.version }}.delga
            blender-democap-tools-${{ github.event.inputs.version }}.zip
            )
          for file in "${files[@]}"; do
            gpg2 --personal-digest-preferences SHA512 --armor --yes --detach-sign \
              --local-user A58A91BCA5C3B2C34CD57ACB8040F88D27F1D0AA \
              --output "${file}.asc" $file
          done
      
      - name: Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: false
          artifactErrorsFailBuild: true
          draft: false
          prerelease: false
          commit: 'main'
          tag: 'v${{ github.event.inputs.version }}'
          name: 'DEMoCap Release ${{ github.event.inputs.version }}'
          body: |
            ${{ github.event.inputs.version }} Release of the DEMoCap.
            
            All information on: https://developer.dragondreams.ch/wiki/doku.php/democap:main
            
            The DEMoCap is a Free Software Application allowing to do Motion Capture using VR equipment.
            
            Requires working installation of Drag[en]gine Game Engine version ${{ github.event.inputs.dragengineVersion }} or newer: https://dragondreams.ch/index.php/dragengine/#downloads-dragengine
            
            GPG signatures for all files are included as .asc files.
          artifacts: >
            DEMoCap-${{ github.event.inputs.version }}.delga,
            blender-democap-tools-${{ github.event.inputs.version }}.zip,
            *.asc
