name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: 'X.Y{.Z}'

jobs:
  distribute:
    uses: ./.github/workflows/distribute.yml
    with:
      version: ${{ github.event.inputs.version }}
      artifact: distribution
      lfscache: false

  blender:
    uses: ./.github/workflows/blender.yml
    with:
      version: ${{ github.event.inputs.version }}
      artifact: blender

  buildmsix:
    needs: [distribute]
    uses: ./.github/workflows/buildmsix.yml
    with:
      version: ${{ github.event.inputs.version }}
      artifactDistribute: distribution
      artifactMsix: msix

  upload:
    needs: [distribute, blender]
    runs-on: ubuntu-latest
    
    steps:
      - name: Get Distribution
        uses: actions/download-artifact@v3
        with:
          name: distribution
      
      - name: Get Blender Scripts
        uses: actions/download-artifact@v3
        with:
          name: blender
      
      - name: Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: false
          artifactErrorsFailBuild: true
          draft: false
          prerelease: false
          commit: 'main'
          tag: 'v${{ github.event.inputs.version }}'
          name: 'DEMoCap Pre-Release ${{ github.event.inputs.version }}'
          body: |
            ${{ github.event.inputs.version }} Release of the DEMoCap.
            
            All information on: https://developer.dragondreams.ch/wiki/doku.php/democap:main
            
            The DEMoCap is a Free Software Application allowing to do Motion Capture using VR equipment.
            
            Requires working installation of Drag[en]gine Game Engine version 1.18 or newer: https://dragondreams.ch/?page_id=152#downloads-dragengine
          artifacts: >
            DEMoCap-${{ github.event.inputs.version }}.delga,
            blender-democap-tools-${{ github.event.inputs.version }}.zip
